// flow-typed signature: 67a308adfd535746965d50f943ee7a3c
// flow-typed version: <<STUB>>/@saritasa/eslint-config-base_v^0.1.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@saritasa/eslint-config-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@saritasa/eslint-config-base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@saritasa/eslint-config-base/index' {
  declare module.exports: $Exports<'@saritasa/eslint-config-base'>;
}
declare module '@saritasa/eslint-config-base/index.js' {
  declare module.exports: $Exports<'@saritasa/eslint-config-base'>;
}
